//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string CodigoProducto { get; set; }
        public string NombreProducto { get; set; }
        public string Precio { get; set; }
        public string Cantidad { get; set; }
        public string Estado { get; set; }
        public string Proveedor { get; set; }
    }
}
